---
# SSL tasks

- name: Create cert directory
  file:
    path: "{{ ssl_cert_directory }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Copy certs
  copy:
    mode: 0600
    owner: root
    group: root
    src: "{{ ssl_local_cert_directory }}/{{ item }}"
    dest: "{{ ssl_cert_directory }}"
  with_items: '{{ ssl_system_certificates }}'
  when: ssl_system_certificates is defined

- name: Copy user certificates
  copy:
    mode: 0600
    owner: "{{ item.owner }}"
    group: "{{ item.group|default(item.owner) }}"
    src: "{{ ssl_local_cert_directory }}/{{ item.name }}"
    dest: "{{ ssl_cert_directory }}/{{ item.name }}"
  with_items: "{{ ssl_user_certificates }}"
  when: ssl_user_certificates is defined

- name: Generate dh params
  command: openssl dhparam -out dhparams.pem 2048
  args:
    creates: "dhparams.pem"
    chdir: "{{ ssl_cert_directory }}"
